#$Id: Makefile,v 1.3 2007/08/03 23:39:33 jchan Exp $

TOP = ../../..
include $(TOP)/Make.misc

BATCH_CONF = lsb.params lsb.users lsb.queues lsb.hosts

brelease:
	$(INST) -m 644 $(BATCH_CONF) $(BRELEASE)/misc/conf_tmpl/
